apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: sample-deployment-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-v1
  namespace: default
  labels:
    app: sample-app
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: applicaiton
          image: {{.Values.app.image}}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
                  optional: false

            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
                  optional: false
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
{{/*---*/}}
{{/*apiVersion: extensions/v1beta1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: my-ingress*/}}
{{/*  annotations:*/}}
{{/*    kubernetes.io/ingress.class: "nginx"*/}}
{{/*spec:*/}}
{{/*  rules:*/}}
{{/*    - http:*/}}
{{/*        paths:*/}}
{{/*          - path: /my/path*/}}
{{/*            backend:*/}}
{{/*              serviceName: my-service*/}}
{{/*              servicePort: 8080*/}}
